Repository mysterycodesociety/mcs-web, pull requests merged in 2019-04, with the labels that each got.

#50 Remove application to intro to ruby ;F
  2018-2019_season.html
  games-for-YOUnity.html
  intro-to-ruby.html
  volunteer.html
Labels: high

#52 6: update sponsors page - Dynamo and ACMW are graduation sponsors ;F
  assets/images/sponsors/acmw.png
  sponsor.html
Labels: high

#55 Add favicon support on all pages, plus device support on index page
  2018-2019_season.html
  assets/images/mcs-favicons/apple-touch-icon-114x114.png
  assets/images/mcs-favicons/apple-touch-icon-120x120.png
  assets/images/mcs-favicons/apple-touch-icon-144x144.png
  assets/images/mcs-favicons/apple-touch-icon-152x152.png
  assets/images/mcs-favicons/apple-touch-icon-57x57.png
  assets/images/mcs-favicons/apple-touch-icon-60x60.png
  assets/images/mcs-favicons/apple-touch-icon-72x72.png
  assets/images/mcs-favicons/apple-touch-icon-76x76.png
  assets/images/mcs-favicons/code.txt
  assets/images/mcs-favicons/favicon-128.png
  assets/images/mcs-favicons/favicon-16x16.png
  assets/images/mcs-favicons/favicon-196x196.png
  assets/images/mcs-favicons/favicon-32x32.png
  assets/images/mcs-favicons/favicon-96x96.png
  assets/images/mcs-favicons/favicon.ico
  assets/images/mcs-favicons/mstile-144x144.png
  assets/images/mcs-favicons/mstile-150x150.png
  assets/images/mcs-favicons/mstile-310x150.png
  assets/images/mcs-favicons/mstile-310x310.png
  assets/images/mcs-favicons/mstile-70x70.png
  classroom-guidelines.html
  code-of-conduct.html
  htmelle-curriculum.html
  index.html
  intro-to-ruby.html
  mission-faq.html
  sponsor.html
  student-projects.html
  volunteer.html
Labels: enhancement

#54 Correct TA name and also fix link to TA picture on any setting
  assets/images/volunteers/mary.jpg
  volunteer.html
Labels: bug, high
